name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          enable-cache: true
      - name: Install dependencies
        run: |
          uv sync --frozen
          playwright install chromium
      - name: Ruff
        run: ruff check .
      - name: Pyright
        run: pyright
      - name: Pytest
        run: pytest -n auto
